import React, { useEffect, useState } from 'react';
import { api } from '../context/AuthContext';
import {
  BellRing,
  ShieldAlert,
  AlertTriangle,
  ShieldCheck,
  Loader,
  Calendar,
  MapPin,
  Flame,
  ArrowRight
} from 'lucide-react';
import { Link } from 'react-router-dom';

interface Alert {
  _id: string;
  message: string;
  locationName: string;
  riskLevel: 'Low Risk' | 'Medium Risk' | 'High Risk';
  createdAt: string;
}

export const AlertHistoryPage: React.FC = () => {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [filter, setFilter] = useState<'All' | 'High Risk' | 'Medium Risk'>('All');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAlerts();
  }, []);

  const fetchAlerts = async () => {
    setLoading(true);
    try {
      const response = await api.get('/alerts');
      setAlerts(response.data);
    } catch (err) {
      console.error('Error fetching alerts:', err);
    } finally {
      setLoading(false);
    }
  };

  const getRiskIndicator = (level: string) => {
    switch (level) {
      case 'High Risk':
        return {
          bg: 'bg-red-950/20 border-red-500/30 text-red-200',
          icon: <ShieldAlert className="text-red-500 shrink-0" size={20} />,
          badge: 'bg-red-500/20 border border-red-500/35 text-red-400'
        };
      case 'Medium Risk':
        return {
          bg: 'bg-amber-950/20 border-amber-500/30 text-amber-200',
          icon: <AlertTriangle className="text-amber-500 shrink-0" size={20} />,
          badge: 'bg-amber-500/20 border border-amber-500/35 text-amber-400'
        };
      default:
        return {
          bg: 'bg-emerald-950/20 border-emerald-500/30 text-emerald-200',
          icon: <ShieldCheck className="text-emerald-500 shrink-0" size={20} />,
          badge: 'bg-emerald-500/20 border border-emerald-500/35 text-emerald-400'
        };
    }
  };

  const filteredAlerts = alerts.filter((alert) => {
    if (filter === 'All') return true;
    return alert.riskLevel === filter;
  });

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6">
        <div>
          <h2 className="text-xl font-extrabold text-white tracking-tight flex items-center gap-2">
            <BellRing size={22} className="text-red-500" />
            <span>Crisis Broadcast Feed</span>
          </h2>
          <p className="text-slate-400 text-xs mt-0.5">Real-time alerts generated by early risk detections and command authorities.</p>
        </div>

        {/* Filter Controls */}
        <div className="flex gap-2 p-1.5 bg-slate-900 border border-slate-800 rounded-xl max-w-sm">
          {(['All', 'High Risk', 'Medium Risk'] as const).map((lvl) => (
            <button
              key={lvl}
              onClick={() => setFilter(lvl)}
              className={`py-1.5 px-3 rounded-lg text-[10px] font-bold uppercase transition-all cursor-pointer ${
                filter === lvl
                  ? 'bg-red-500/10 border border-red-500/20 text-red-400 shadow-md shadow-red-500/5'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {lvl.replace(' Risk', '')}
            </button>
          ))}
        </div>
      </div>

      {loading ? (
        <div className="glass-panel border border-slate-800 rounded-2xl p-16 text-center">
          <Loader size={24} className="animate-spin text-red-500 mx-auto mb-4" />
          <span className="text-xs text-slate-400">Syncing warning feeds...</span>
        </div>
      ) : filteredAlerts.length === 0 ? (
        <div className="glass-panel border border-slate-800 rounded-2xl p-16 text-center space-y-4">
          <ShieldCheck size={48} className="text-emerald-500/80 mx-auto animate-pulse" />
          <div className="space-y-1">
            <h4 className="text-sm font-bold text-slate-350">early warning network stable</h4>
            <p className="text-xs text-slate-500">There are no active {filter !== 'All' ? filter.toLowerCase() : ''} emergency notices across zones.</p>
          </div>
          <div className="pt-2">
            <Link
              to="/dashboard"
              className="px-4 py-2 bg-slate-800 hover:bg-slate-750 text-slate-200 border border-slate-700 text-xs font-bold rounded-xl transition-all inline-flex items-center gap-1.5"
            >
              <span>Dashboard Overview</span>
              <ArrowRight size={12} />
            </Link>
          </div>
        </div>
      ) : (
        <div className="space-y-4 max-w-4xl">
          {filteredAlerts.map((alert) => {
            const styles = getRiskIndicator(alert.riskLevel);
            return (
              <div
                key={alert._id}
                className={`p-5 rounded-2xl border flex flex-col sm:flex-row items-start gap-4 transition-all duration-300 hover:-translate-y-0.5 hover:shadow-lg ${styles.bg}`}
              >
                {/* Severity Icon */}
                <div className="p-2.5 bg-slate-950/40 border border-slate-850 rounded-xl shrink-0">
                  {styles.icon}
                </div>

                {/* Content */}
                <div className="flex-1 space-y-3">
                  <div className="flex flex-wrap items-center gap-3">
                    <span className={`px-2 py-0.5 rounded text-[8px] font-extrabold uppercase ${styles.badge}`}>
                      {alert.riskLevel}
                    </span>
                    <span className="text-xs text-slate-400 flex items-center gap-1">
                      <MapPin size={12} className="text-slate-500" />
                      {alert.locationName}
                    </span>
                    <span className="text-xs text-slate-500 flex items-center gap-1 ml-auto">
                      <Calendar size={12} />
                      {new Date(alert.createdAt).toLocaleString()}
                    </span>
                  </div>
                  <p className="text-xs text-slate-200 leading-relaxed font-semibold">
                    {alert.message}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
export default AlertHistoryPage;
